### ISSUE TITLE
Choose blog platform

### ISSUE THREAD

**Issue by HeMan** [erik78se/robojoy#11]
hackaday.io or something else?

**Comment by 101208** [comment]
wha is that

**Comment by 101208** [comment]
heman how may i help you

**Comment by HeMan** [comment]
Let's use github pages!

**Comment by HeMan** [comment]
Should we really? It's connected to a user name, not a project, see https://pages.github.com/

**Comment by HeMan** [comment]
Or maybe was I a bit to fast. You _could_ have a project page.

**Comment by HeMan** [comment]
@erik78se Enable github pages for this repo, chose no theme and point it to /docs in master branch. I'll fix Jekyll after that.

**Comment by HeMan** [comment]
@erik78se Enable github pages on /docs and mast branch. Choose a decent theme.

**Comment by erik78se** [comment]
https://erik78se.github.io/robojoy/

**Comment by HeMan** [comment]
Solved by 1683e5ea88c1366a143ba8e77022dd454fbab78d
