### ISSUE TITLE
Decide on distro

### ISSUE THREAD

**Issue by HeMan** [erik78se/robojoy#40]
- Armbian
- Ubuntu 
- Fedora
- Alpine 
- Debian/Rasbpian

**Comment by HeMan** [comment]
I've tried Raspbian and it works good on RPi3 wrt hardware like wifi. Docker is also easy to add, but I haven't tried snaps yet. Could you @erik78se test snaps on it when you get you new Rpi?

**Comment by erik78se** [comment]
Ubuntu MATE 16.04.1

**Comment by HeMan** [comment]
https://downloads.ubiquityrobotics.com/pi.html
