### ISSUE TITLE
Learn about encoders

### ISSUE THREAD

**Issue by erik78se** [erik78se/robojoy#48]
Watch this:

https://www.youtube.com/watch?v=oLBYHbLO8W0

**Comment by HeMan** [comment]
@erik78se I think we could close this one once we have connected our encoders, right?

**Comment by HeMan** [comment]
Depends on #6

**Comment by erik78se** [comment]
Here is some code: https://github.com/merose/ROSRobotControl

**Comment by HeMan** [comment]
Both @erik78se and @HeMan has code that reads the encoder in Arduino.
